In [1]:
import torch

In [21]:
# 0차원(rank) 텐서 -> 스칼라
# 1차원 텐서 -> 벡터
# 2차원 텐서 -> 매트릭스
# 3차원 이상 텐서 -> n차원 텐서
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [22]:
# 텐서의 size, shape, ndimension
print("Size:", x.size())
print("Shape:", x.shape)
print("rank(dimension):", x.ndimension())

Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
rank(dimension): 2


In [23]:
# unsqueeze(), tensor의 랭크 증가
x = torch.unsqueeze(x, 0) # index에 따라서 Size의 index에 rank가 추가된다.
print(x)
print("Size:", x.size()) # [3, 3] -> [1, 3, 3](index = 0), [3, 3] -> [3, 1, 3](index = 1)
print("rank:", x.ndimension())

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
Size: torch.Size([3, 1, 3])
rank: 3


In [24]:
# squeeze(), tensor의 랭크 감소
x = torch.squeeze(x) # size/shape 중 1인 index를 제거
print(x)
print("Size:", x.shape)
print("rank:", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
rank: 2


In [30]:
# view(), rank 변경 및 tensor의 모양 변경 가능
x = x.view(9)
print(x)
print("Size:", x.size())
print("rank:", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
rank: 1


In [31]:
# unsqueeze, squeeze, view는 tensor가 포함하고 있는 원소의 수를 유지해야 한다.
try:
    x = x.view(2,4)
except Exception as e:
    print(e)

shape '[2, 4]' is invalid for input of size 9
